inherit_from:
  - .rubocop-txi.yml

# Overrides can go here, but try to conform to TXI standards when possible.
#
# Example...
# Metrics/CyclomaticComplexity:
#   Enabled: false # We've got nasty methods!
#
