#!/bin/sh

# We choose not to auto-correct so that the return code is non-0
# causing the pre-push to prevent the 'git push' from doing it.
# This will run Rubocop on all files tracked with git, ignoring any files in the
# repo's .gitignore or your .gitignore_global.

bundle exec rubocop --force-exclusion `git ls-tree -r HEAD --name-only`
